require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HeadlinesController do

  # This should return the minimal set of attributes required to create a valid
  # Headline. As you add validations to Headline, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HeadlinesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all headlines as @headlines" do
      headline = Headline.create! valid_attributes
      get :index, {}, valid_session
      assigns(:headlines).should eq([headline])
    end
  end

  describe "GET show" do
    it "assigns the requested headline as @headline" do
      headline = Headline.create! valid_attributes
      get :show, {:id => headline.to_param}, valid_session
      assigns(:headline).should eq(headline)
    end
  end

  describe "GET new" do
    it "assigns a new headline as @headline" do
      get :new, {}, valid_session
      assigns(:headline).should be_a_new(Headline)
    end
  end

  describe "GET edit" do
    it "assigns the requested headline as @headline" do
      headline = Headline.create! valid_attributes
      get :edit, {:id => headline.to_param}, valid_session
      assigns(:headline).should eq(headline)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Headline" do
        expect {
          post :create, {:headline => valid_attributes}, valid_session
        }.to change(Headline, :count).by(1)
      end

      it "assigns a newly created headline as @headline" do
        post :create, {:headline => valid_attributes}, valid_session
        assigns(:headline).should be_a(Headline)
        assigns(:headline).should be_persisted
      end

      it "redirects to the created headline" do
        post :create, {:headline => valid_attributes}, valid_session
        response.should redirect_to(Headline.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved headline as @headline" do
        # Trigger the behavior that occurs when invalid params are submitted
        Headline.any_instance.stub(:save).and_return(false)
        post :create, {:headline => {  }}, valid_session
        assigns(:headline).should be_a_new(Headline)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Headline.any_instance.stub(:save).and_return(false)
        post :create, {:headline => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested headline" do
        headline = Headline.create! valid_attributes
        # Assuming there are no other headlines in the database, this
        # specifies that the Headline created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Headline.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => headline.to_param, :headline => { "these" => "params" }}, valid_session
      end

      it "assigns the requested headline as @headline" do
        headline = Headline.create! valid_attributes
        put :update, {:id => headline.to_param, :headline => valid_attributes}, valid_session
        assigns(:headline).should eq(headline)
      end

      it "redirects to the headline" do
        headline = Headline.create! valid_attributes
        put :update, {:id => headline.to_param, :headline => valid_attributes}, valid_session
        response.should redirect_to(headline)
      end
    end

    describe "with invalid params" do
      it "assigns the headline as @headline" do
        headline = Headline.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Headline.any_instance.stub(:save).and_return(false)
        put :update, {:id => headline.to_param, :headline => {  }}, valid_session
        assigns(:headline).should eq(headline)
      end

      it "re-renders the 'edit' template" do
        headline = Headline.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Headline.any_instance.stub(:save).and_return(false)
        put :update, {:id => headline.to_param, :headline => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested headline" do
      headline = Headline.create! valid_attributes
      expect {
        delete :destroy, {:id => headline.to_param}, valid_session
      }.to change(Headline, :count).by(-1)
    end

    it "redirects to the headlines list" do
      headline = Headline.create! valid_attributes
      delete :destroy, {:id => headline.to_param}, valid_session
      response.should redirect_to(headlines_url)
    end
  end

end
